/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

//class App {
//    val greeting: String
//        get() {
//            return "Hello world."
//        }
//}
//
//fun main(args: Array<String>) {
//    println(App().greeting)
//}
//

import org.jooby.Jooby.*
import org.jooby.Kooby

class App : Kooby({
    get {
        val name = param("name").value("Kotlin")
        "Hello $name!"
    }
})

fun main(args: Array<String>) {
    run(::App, args)
}

//import org.jooby.json.Jackson
//import org.jooby.apitool.ApiTool
//
//data class Hello(val hello: String)
//
//class App : Kooby({
//    use(Jackson())
//    get("/hello/{name}") { Hello(param("name").value()) }
//})