/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example

import io.javalin.Javalin

fun main(args: Array<String>) {
    val app = Javalin.create().start(7000)
    app.get("/") { ctx -> ctx.result("Hello javalin World") }
}
